spring:
  profiles:
    active: company
  # 使用CGLIB来实现AOP,不配置则默认使用Java的实现
  aop:
    proxy-target-class=true
  server:
    port: 8080

mybatis:
  # 映射文件所在路径
#  mapper-locations: classpath:mapper/*.xml
  # pojo类所在包路径
  type-aliases-package: com.ryang.springboot.pojo

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

