# \u7B14\u8BB0\u672C\u73AF\u5883\u914D\u7F6E

server:
  port:8080
# MySQL\u6570\u636E\u5E93\u914D\u7F6E
spring:
  profiles:person
  datasource:
    name:mybatis
    #\u4F7F\u7528druid\u8FDE\u63A5\u6C60
    type: com.alibaba.druid.pool.DruidDataSource
      #druid\u76F8\u5173\u914D\u7F6E
      druid:
        #\u914D\u7F6E\u57FA\u672C\u5C5E\u6027
        ryang:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          name: ryang
          url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
          password: root
          test:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            name: zentaopro
            url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
            username: root
            password: root

