spring:
  profiles:
    active: company
# 公司环境配置(所有服务在linux的docker上)
server:
  port: 8080

mybatis:
  # 映射文件所在路径
#  mapper-locations: classpath:mapper/*.xml
  # pojo类所在包路径
  type-aliases-package: com.ryang.springboot.pojo

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql